/*
** EPITECH PROJECT, 2023
** B-CPP-500-NAN-5-1-rtype-lucas.hauszler [WSL: Ubuntu]
** File description:
** KeyToString
*/

#include "KeyToString.hpp"

std::string rtype::utils::keyToString(raylib::KeyboardKey key)
{
    const static std::map<raylib::KeyboardKey, std::string> keyToStr =
    {
        {raylib::KEY_APOSTROPHE, "APOSTROPHE"},
        {raylib::KEY_COMMA, "COMMA"},
        {raylib::KEY_MINUS, "MINUS"},
        {raylib::KEY_PERIOD, "PERIOD"},
        {raylib::KEY_SLASH, "SLASH"},
        {raylib::KEY_ZERO, "ZERO"},
        {raylib::KEY_ONE, "ONE"},
        {raylib::KEY_TWO, "TWO"},
        {raylib::KEY_THREE, "THREE"},
        {raylib::KEY_FOUR, "FOUR"},
        {raylib::KEY_FIVE, "FIVE"},
        {raylib::KEY_SIX, "SIX"},
        {raylib::KEY_SEVEN, "SEVEN"},
        {raylib::KEY_EIGHT, "EIGHT"},
        {raylib::KEY_NINE, "NINE"},
        {raylib::KEY_SEMICOLON, "SEMICOLON"},
        {raylib::KEY_EQUAL, "EQUAL"},
        {raylib::KEY_A, "A"},
        {raylib::KEY_B, "B"},
        {raylib::KEY_C, "C"},
        {raylib::KEY_D, "D"},
        {raylib::KEY_E, "E"},
        {raylib::KEY_F, "F"},
        {raylib::KEY_G, "G"},
        {raylib::KEY_H, "H"},
        {raylib::KEY_I, "I"},
        {raylib::KEY_J, "J"},
        {raylib::KEY_K, "K"},
        {raylib::KEY_L, "L"},
        {raylib::KEY_M, "M"},
        {raylib::KEY_N, "N"},
        {raylib::KEY_O, "O"},
        {raylib::KEY_P, "P"},
        {raylib::KEY_Q, "Q"},
        {raylib::KEY_R, "R"},
        {raylib::KEY_S, "S"},
        {raylib::KEY_T, "T"},
        {raylib::KEY_U, "U"},
        {raylib::KEY_V, "V"},
        {raylib::KEY_W, "W"},
        {raylib::KEY_X, "X"},
        {raylib::KEY_Y, "Y"},
        {raylib::KEY_Z, "Z"},
        {raylib::KEY_LEFT_BRACKET, "LEFT_BRACKET"},
        {raylib::KEY_BACKSLASH, "BACKSLASH"},
        {raylib::KEY_RIGHT_BRACKET, "RIGHT_BRACKET"},
        {raylib::KEY_GRAVE, "GRAVE"},
        {raylib::KEY_SPACE, "SPACE"},
        {raylib::KEY_ESCAPE, "ESCAPE"},
        {raylib::KEY_ENTER, "ENTER"},
        {raylib::KEY_TAB, "TAB"},
        {raylib::KEY_BACKSPACE, "BACKSPACE"},
        {raylib::KEY_INSERT, "INSERT"},
        {raylib::KEY_DELETE, "DELETE"},
        {raylib::KEY_RIGHT, "RIGHT"},
        {raylib::KEY_LEFT, "LEFT"},
        {raylib::KEY_DOWN, "DOWN"},
        {raylib::KEY_UP, "UP"},
        {raylib::KEY_PAGE_UP, "PAGE_UP"},
        {raylib::KEY_PAGE_DOWN, "PAGE_DOWN"},
        {raylib::KEY_HOME, "HOME"},
        {raylib::KEY_END, "END"},
        {raylib::KEY_CAPS_LOCK, "CAPS_LOCK"},
        {raylib::KEY_SCROLL_LOCK, "SCROLL_LOCK"},
        {raylib::KEY_NUM_LOCK, "NUM_LOCK"},
        {raylib::KEY_PRINT_SCREEN, "PRINT_SCREEN"},
        {raylib::KEY_PAUSE, "PAUSE"},
        {raylib::KEY_F1, "F1"},
        {raylib::KEY_F2, "F2"},
        {raylib::KEY_F3, "F3"},
        {raylib::KEY_F4, "F4"},
        {raylib::KEY_F5, "F5"},
        {raylib::KEY_F6, "F6"},
        {raylib::KEY_F7, "F7"},
        {raylib::KEY_F8, "F8"},
        {raylib::KEY_F9, "F9"},
        {raylib::KEY_F10, "F10"},
        {raylib::KEY_F11, "F11"},
        {raylib::KEY_F12, "F12"},
        {raylib::KEY_LEFT_SHIFT, "LEFT_SHIFT"},
        {raylib::KEY_LEFT_CONTROL, "LEFT_CONTROL"},
        {raylib::KEY_LEFT_ALT, "LEFT_ALT"},
        {raylib::KEY_LEFT_SUPER, "LEFT_SUPER"},
        {raylib::KEY_RIGHT_SHIFT, "RIGHT_SHIFT"},
        {raylib::KEY_RIGHT_CONTROL, "RIGHT_CONTROL"},
        {raylib::KEY_RIGHT_ALT, "RIGHT_ALT"},
        {raylib::KEY_RIGHT_SUPER, "RIGHT_SUPER"},
        {raylib::KEY_KB_MENU, "KB_MENU"},
        {raylib::KEY_KP_0, "KP_0"},
        {raylib::KEY_KP_1, "KP_1"},
        {raylib::KEY_KP_2, "KP_2"},
        {raylib::KEY_KP_3, "KP_3"},
        {raylib::KEY_KP_4, "KP_4"},
        {raylib::KEY_KP_5, "KP_5"},
        {raylib::KEY_KP_6, "KP_6"},
        {raylib::KEY_KP_7, "KP_7"},
        {raylib::KEY_KP_8, "KP_8"},
        {raylib::KEY_KP_9, "KP_9"},
        {raylib::KEY_KP_DECIMAL, "KP_DECIMAL"},
        {raylib::KEY_KP_DIVIDE, "KP_DIVIDE"},
        {raylib::KEY_KP_MULTIPLY, "KP_MULTIPLY"},
        {raylib::KEY_KP_SUBTRACT, "KP_SUBTRACT"},
        {raylib::KEY_KP_ADD, "KP_ADD"},
        {raylib::KEY_KP_ENTER, "KP_ENTER"},
        {raylib::KEY_KP_EQUAL, "KP_EQUAL"},
        {raylib::KEY_BACK, "BACK"},
        {raylib::KEY_MENU, "MENU"},
        {raylib::KEY_VOLUME_UP, "VOLUME_UP"},
        {raylib::KEY_VOLUME_DOWN, "VOLUME_DOWN"}
    };
    const auto it = keyToStr.find(key);

    if (it == keyToStr.end())
        return "UNKNOWN";
    return it->second;
}
