name: Feature Request
description: Suggest an idea for this project
title: "<title>"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting
      placeholder: Describe the feature you are requesting
      render: markdown
    validations:
      required: true
  - type: textarea
    id: feature-test-cases
    attributes:
      label: Test Cases
      description: Describe the test cases to do to prove that the feature works
      placeholder: Describe the test cases to do to prove that the feature works
      render: markdown
