name: Create Release on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the tag name from the event
        id: get_tag_name
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"

      - name: Create Release
        id: create_release
        if: steps.get_tag_name.outputs.tag_name != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
          release_name: Release ${{ steps.get_tag_name.outputs.tag_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
